### ISSUE TITLE
Question: does vine actually support FormData?

### ISSUE THREAD

**Issue by jaysson** [vinejs/vine#11]
### Package version

1.5.1

### Describe the bug

On the website, I see
> Built for validating form data and JSON payloads. [Learn more](https://vinejs.dev/docs/introduction#built-for-validating-form-data-and-json-payloads).

and I assumed I can pass a `FormData` object as data. But that doesn't seem to work.

```js
import vine from '@vinejs/vine';

const schema = vine.object({ username: vine.string() });

const data = new FormData();
data.append('username', 'johndoe');

vine.validate({ schema, data }).then(console.log).catch(console.error);
// Throws 'The username field must be defined'
```
Are we supposed to create a plain object from the `FormData` before validation, possibly using something like https://www.npmjs.com/package/reformdata?

**Comment by thetutlage** [comment]
Hello

Yeah, I see how that can be confusing. VineJS does not support the FormData type, but instead it handles the serialization behavior of FormData. 

So yes, you will have to convert it to a regular Object first. 

Infact, if you are interested, you can make a package for this and use the extensible API for VineJS to add a new method called `vine.validateFormData()`. Lemme know if you need help with that

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by aspirin2d** [comment]
May be it's a good idea to support `Formdata`.
