### ISSUE TITLE
Type error: Type parameter declaration expected.

### ISSUE THREAD

**Issue by leshadavay** [vinejs/vine#21]
### Package version

1.6.0

### Describe the bug

I'm getting  `Type error: Type parameter declaration expected.` error message coming from `./node_modules/@vinejs/vine/build/index.d.ts:194:24` while I try to build my project (Next.js api)

(there's no any errors firing if I run this project on development environment: `npm run dev`)

```
  const schema = vine.object({
    authorization: vine.string().minLength(8),
  });
  const data = {
    authorization: "111",
  };

  const result = await vine.validate({
    data,
    schema,
  });
  
  ```

Update: it fires same type error if I only import vinejs package top of the file: `import vine from "@vinejs/vine";`

npm: 9.6.7
node: v18.17.0

**Comment by RomainLanz** [comment]
Hey @leshadavay! 👋🏻 

Please provide a repository with the minimum amount of code to reproduce your issue.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
