### ISSUE TITLE
Feature request link is broken

### ISSUE THREAD

**Issue by ShivamJoker** [vinejs/vine#22]
### Package version

^1.6.0

### Describe the bug

I wanted to open feature request for adding the `default` value option in schema like we have in zod.
But seems like the link is broken.

**Comment by RomainLanz** [comment]
Hey @ShivamJoker! 👋🏻 

On a side note, mimicking the Zod `default` behavior is already doable.
We even have a more powerful system using the `parse` method.

```ts
function assignDefaultRole(value: unknown) {
  if (!value) {
    return 'guest'
  }
  
  return value
}

const schema = vine.object({
  role: vine.string().parse(assignDefaultRole)
})
```

📚 https://vinejs.dev/docs/schema_101#parsing-input-value

**Comment by ShivamJoker** [comment]
Thanks @RomainLanz for the quick response.
I see, but is there any way we can extend this and make it similar to `v.string().default('value')`?

**Comment by RomainLanz** [comment]
Not sure why adding a new API would be useful.
As said, it is more powerful and could be refactored down to the following:
```ts
v.string().parse(v => v ?? 'default')
```

**Comment by ShivamJoker** [comment]
I know it can be powerful and we can achieve the same thing, but having an API would reduce the lines of code which we have to write a function for every default.

**Comment by thetutlage** [comment]
You can extend the `StringSchema` class and docs already cover how to extend schema classes.
