### ISSUE TITLE
Fix typo in Symbol(schema_nme) on compiled schemas

### ISSUE THREAD

**Issue by arthur-er** [vinejs/vine#26]
### Package version

1.7.0

### Describe the bug

Change `Symbol(schema_nme)` to `Symbol(schema_name)`

**Comment by RomainLanz** [comment]
Hey @arthur-er! 👋🏻 

Could you do a PR?

**Comment by Izurii** [comment]
@RomainLanz I just did a PR fixing the typo. #36
