### ISSUE TITLE
How to use vinejs with fastify ?

### ISSUE THREAD

**Issue by pullmann4rent** [vinejs/vine#28]
### Package version

1.7.1

### Describe the bug

How can I add vinejs in this schema in fastify ?

```
  app.post(
    '/register',
    {
      schema: {
        body: $ref('createUserSchema'),
        response: {
          201: $ref('createUserResponseSchema'),
        },
      },
    },
    () => {},
```

**Comment by RomainLanz** [comment]
Hey @pullmann4rent! 👋🏻 

I believe `fastify` uses, by default, the `ajv` schema to validate anything. So I don't think you could use `vine` here directly.

You can use `vine` directly inside your route handler.

```ts
app.post('/register', async (request) => {
  const payload = await myValidator.validate(request.body)
})
```

I recommend opening an issue on `fastify` repository to know if an adapter could be created to work in their schema system. Nevertheless, it is not something we plan to create (an adapter) in the short term.

**Comment by thetutlage** [comment]
I already created an example with fastify earlier. Here it is https://github.com/vinejs/vinejs-example-fastify

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
