### ISSUE TITLE
How can I import the `ValidationOptions` type?

### ISSUE THREAD

**Issue by Atinux** [vinejs/vine#3]
Trying to build an abstraction for vine for h3, but cannot import it:

```ts
import vine, { errors, ValidationOptions } from '@vinejs/vine'
import type { H3Event } from 'h3'

export const v = vine

export async function validateParams(event: H3Event, schema: ValidationOptions) {
  const data = event.context.params || {}
  try {
    return await v.validate({
      data,
      schema
    })
  } catch (error: any) {
    if (error instanceof errors.E_VALIDATION_ERROR) {
      throw createError({
        statusCode: 400,
        message: error.message
      })
    }
    throw createError({
      statusCode: 500,
      message: error.message || 'Internal server error'
    })
  }
}
```

Thanks for your work ❤️

**Comment by thetutlage** [comment]
Hello @Atinux 👋

Thanks for giving it a try.

You can import it from the `@vinejs/vine/types` submodule. 

```ts
import { ValidationOptions } from '@vinejs/vine/types' 
```

**Comment by thetutlage** [comment]
<img width="617" alt="Screenshot 2023-06-17 at 9 52 01 AM" src="https://github.com/vinejs/vine/assets/1706381/57da370e-7c7d-4b82-a10c-a21821decafc">

Weird. Works fine for me. Between, I have set the `module` to `NodeNext` in `tsconfig.json` file. I think with CommonJS, TypeScript does not resolve the `exports` from `package.json` file.

**Comment by chrisbbreuer** [comment]
There is an issue with the types imports. A temporary workaround would be:

```js
import type { ValidationOptions } from '@vinejs/vine/build/src/types'
```

Will see if I can find the reason

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by biniyammoges** [comment]
<img width="799" alt="Screenshot 2024-06-21 at 2 21 07 PM" src="https://github.com/vinejs/vine/assets/80150851/7dbfbb55-feff-4008-bb24-8aa0c77147ca">

I am getting the same error,
Is this issue not fixed yet?

**Comment by RomainLanz** [comment]
> I am getting the same error, Is this issue not fixed yet?

Have you correctly set the `module` property of your `tsconfig.json`?
Also, you should be using `import type` instead of only `import`.
