### ISSUE TITLE
Can vinejs support verifying bigint field types

### ISSUE THREAD

**Issue by h25302** [vinejs/vine#31]
### Package version

1.7.1

### Describe the bug

be similar to:    **vine.bigint()**

**Comment by RomainLanz** [comment]
Probably the same type of validation that the one we had in AdonisJS 5.

This means parsing a huge number sent as a string to be cast in `bigint` by the validator.

**Comment by thetutlage** [comment]
Okay, so basically attempting to cast any string and number values to `BigInt` and report error if unable to do so

**Comment by thetutlage** [comment]
I will let this issue be on hold for a while and see if others wants to share what sort of validation rules they need related to a BigInt value.

For example, with numbers we have `min`, `max`, `range` and so on. So I want to collect the initial set of rules to implement for the `BigInt` as well.

**Comment by thetutlage** [comment]
Closing issue, since it hasn't received any more requests.
