### ISSUE TITLE
[NEED HELP] Cannot configure my project using Vinejs

### ISSUE THREAD

**Issue by doantu05150** [vinejs/vine#32]
### Package version

@vinejs/vine@1.7.1 

### Describe the bug

I try to create a Nodejs project using Typescript + Express + Prisma + Vinejs

I know VineJS is an ESM-only package but I cannot configure it, There are some bugs that I don't know how to fix. Please someone help me or create an MR on this [repo](https://github.com/doantu05150/nodejs-express-typescript-postgress-vinejs-demo). Thank you so much

Here are all the packages used.

"dependencies":  

    "@prisma/client": "^5.8.1",

    "@vinejs/vine": "^1.7.1",

    "dotenv": "^16.3.1",

    "express": "^4.18.2"

  "devDependencies": 

    "@types/express": "^4.17.21",

    "@types/node": "^20.11.0",

    "nodemon": "^3.0.2",

    "prettier-plugin-prisma": "^5.0.0",

    "prisma": "^5.8.0",

    "ts-node": "^10.9.2",

    "typescript": "^5.3.3"

<img width="1051" alt="image" src="https://github.com/vinejs/vine/assets/29808554/78cafc9a-9c39-46ef-a271-80c19e05c950">

### Reproduction repo

https://github.com/doantu05150/nodejs-express-typescript-postgress-vinejs-demo

**Comment by RomainLanz** [comment]
Hey @doantu05150! 👋🏻 

This has nothing to do with Vine. You are configuring `nodemon` to run a file that does not exist.

**Comment by doantu05150** [comment]
Yes, my bad. Thank you
