### ISSUE TITLE
[feat] synchronous support

### ISSUE THREAD

**Issue by MentalGear** [vinejs/vine#37]
### Package version

latest

### Describe the bug

Not a bug, feature request but the form loops back towards the same github issues page.

Allow synchronous validation, so it can be used in object constructors. I know, you're 'aiming' for form validation, but a little change can make vine much more useful as a general validation library instead of using many.

Meanwhile, I'll head back to zod or superstruct for a one-stop-shop high performance lib.

**Comment by thetutlage** [comment]
Yeah not something I want to do. As you mentioned, Zod and Superstruct works great for those use-cases and helps the decision making simpler between what to choose.
