### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by guillaumervls** [vinejs/vine#38]
### Package version

1.7.1

### Describe the bug

Hi and thanks for the work on VineJS!

Is there a way to add a transform/mutation to specify a default value when something is optional / `undefined`?

Like Zod's [`.default`](https://zod.dev/?id=default):
```js
const stringWithDefault = z.string().default("tuna");
stringWithDefault.parse(undefined); // => "tuna"
```

Cheers!

**Comment by RomainLanz** [comment]
Hey @guillaumervls! 👋🏻 

Use the [`parse()`](https://vinejs.dev/docs/schema_101#parsing-input-value) method.

```ts
vine.string().parse(v => v ?? 'Unknown')
```

**Comment by guillaumervls** [comment]
Thanks for your answer @RomainLanz! 🙏 

(BTW, feel free to close/keep this issue depending on whether you're considering adding a dedicated function or not.)

**Comment by RomainLanz** [comment]
The `parse` method is a bit more verbose, but it is also way more powerful, so we are not going to extend Vine's API to add a new `default` method.

Closing. 👍🏻

**Comment by theoludwig** [comment]
What about `.number` fields? There are no `.parse` method, I tried with `.transform` but it doesn't seem to work.

```ts
const requestValidator = vine.compile(
  vine.object({
    limit: vine
      .number()
      .withoutDecimals()
      .range([1, 100])
      .optional()
      .transform((value) => {
        const valueAsNumber = vine.helpers.asNumber(value)
        return valueAsNumber ?? 5
      }),
  }),
)
```

Then in my Adonis controller:
```ts
const payload = await context.request.validateUsing(requestValidator)

payload.limit // `undefined` but it should be 5
```

**Comment by theoludwig** [comment]
Workaround is to do it manually `payload.limit ?? 5` where `.validate` is called, but I'd rather define the default value in the schema.

**Comment by sergefabre** [comment]
Hello. 
the method "default" of ZOD allows you to assign a value (null for example) if the property is absent in the validator input. I would like to find this behavior with vinejs, but I can't. Any idea?

**Comment by radiumrasheed** [comment]
> Hey @guillaumervls! 👋🏻
> 
> Use the [`parse()`](https://vinejs.dev/docs/schema_101#parsing-input-value) method.
> 
> ```ts
> vine.string().parse(v => v ?? 'Unknown')
> ```

I suggest we have a page for this in the documentation. it's usual for devs to look for this particular API in a validation library. I looked but didn't find anything until I came to github issues
