### ISSUE TITLE
Docs: Add information about bundle size

### ISSUE THREAD

**Issue by ShivamJoker** [vinejs/vine#4]
Thanks for the great work.
I would really appreciate if we can have some bundle size comparisons as well.

On [bundlephobia](https://bundlephobia.com/package/@vinejs/vine@1.4.0) it shows:
43.5kB
Minified + Gzipped

Where Zod is just:
13.1kB
Minified + Gzipped

**Comment by thetutlage** [comment]
VineJS is meant to be used on backend, where I think bundle size is not that relevant. I do not see it getting bundled in the frontend code

**Comment by ShivamJoker** [comment]
Oh I see. 
But when you are deploying to Lambda and there are bunch of other libraries which will make the entire code base huge.

**Comment by thetutlage** [comment]
With Lambda yes, the bundle size can slow down the cold starts. But, in Node.js it does not really matter.

Also, for me, having more battle tested rules is far important than saving few bytes.

Still, you can send me a PR for the README file to add a badge for bundlephobia. You can use https://shields.io/
