### ISSUE TITLE
Question: How can test rest controllers with postman

### ISSUE THREAD

**Issue by Steveperi** [vinejs/vine#43]
### Package version

adonis 6

### Describe the bug

I build an app with adonis 6 and inertia and I create resource controllers. The problem is that when I send request from postman for testing reason, the request doesn't return json format. Return json only when sending from vua app with axios
![Screenshot 2024-03-19 at 3 29 49 PM](https://github.com/vinejs/vine/assets/6014414/31e7f86e-82d0-40d3-90cf-cba434d693ba)

**Comment by RomainLanz** [comment]
Hey @Steveperi! 👋🏻 

You must specify what you want as an answer by using the [`Accept` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept).
