### ISSUE TITLE
`field` field of Adonis validation messages

### ISSUE THREAD

**Issue by Xstoudi** [vinejs/vine#46]
### Package version

2.0.0

### Describe the bug

I created a unique rule for VineObject, but I don't really understand where I forgot to pass the `field` value on message object.
I understand there is none by default, but is it possible to customize it?
```
 messages: [
    {
      message: 'The [section_id, rank] group is not unique',
      rule: 'uniqueComposed',
      field: ''
    }
  ]
```

For example, here I would like to show the error on the `rank` field in the frontend, so I would like `field` to equals `rank`.

**Comment by thetutlage** [comment]
Can you share how you report the error and how this unique rule is used?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
