### ISSUE TITLE
ValidationError uses V8's stack trace API which breaks on Firefox

### ISSUE THREAD

**Issue by simoneNEMO** [vinejs/vine#49]
### Package version

v2.0.0

### Describe the bug

Since you recently made some efforts to bring VineJS from Node to the Browser (h/t @Julien-R44) I wanted to flag that `ValidationError` uses [`Error.captureStackTrace`](https://github.com/vinejs/vine/blob/62d450c1d320cdd5cd00a7299fe7a447cff8240c/src/errors/validation_error.ts#L32) which is a feature from V8's stack trace API and breaks on non V8 environments like Firefox.

Of course I understand VineJS is still officially a Node library but it is great to use on the Browser side as well, especially since it is already almost fully compatible.

**Comment by thetutlage** [comment]
What's the alternative to using `Error.captureStackTrace` in cross-browser environment?

**Comment by simoneNEMO** [comment]
There is indeed no decent solution but seems most of codebases out there that want to be cross-browser engine compatible use something like [this](https://github.com/sindresorhus/capture-stack-trace/blob/main/index.js).

Of course is not the job of VineJS to adapt to every browser but opened this issue for awareness and to start the conversation.

**Comment by lahgolz** [comment]
Is this planned? I fixed the issue on one of my projects using Yarn's patch feature, but now contributors can only use Yarn when working on it because it uses a protocol unknown to other package managers.
