### ISSUE TITLE
Improving Error Messages for Array Indexing

### ISSUE THREAD

**Issue by erwinstone** [vinejs/vine#5]
I recently tried using vine with the scheme below.

```typescript
import vine, { errors } from '@vinejs/vine'

try {
  const test = await vine.validate({
    schema: vine.object({
      invoice: vine.string(),
      items: vine.array(vine.object({
        qty: vine.number().min(1),
      })).minLength(1),
    }),
    data: {
      invoice: 'TEST 123',
      items: [
        {
          qty: 2,
        },
        {
          qty: 0,
        },
      ],
    },
  })
  console.log(test)
}
catch (error) {
  if (error instanceof errors.E_VALIDATION_ERROR) {
    console.log(error.messages)
  }
}
```

```typescript
[
  {
    message: 'The qty field must be at least 1',
    rule: 'min',
    field: 'items.*.qty',
    meta: { min: 1 }
  }
]
```

In my opinion, it would be more helpful to display the index number corresponding to an invalid index in the error message for an array, rather than simply showing an asterisk symbol.

In that case, it would be better to display `items.1.qty` instead of `items.*.qty`.

**Comment by jaysson** [comment]
Also, it would be great to have an `arrayPath` in `FieldContext`. For ex. the above field can be `['items', 0, 'qty']`. I can then format it easily in a custom error reporter. In my case I want to format it as `items[0][qty]`, like how PHP & RoR handle forms.

**Comment by gurvancampion** [comment]
I'm also having the same need inside a custom error reporter to determine to which field belongs this error.
To avoid breaking changes, maybe it could be an additional information added somewhere like in the `meta` object:
```ts 
meta: { parentIndex: 0 }
```

**Comment by thetutlage** [comment]
I do find suggestions in this issue useful. But, I think it will a little hard to implement this without sacrificing the performance. I am okay with a minor performance hit.

I am going on sit on this issue for a while and pick it up later (once I have some ideas)

**Comment by thetutlage** [comment]
Shipped in https://github.com/vinejs/vine/releases/tag/v2.0.0-0
