### ISSUE TITLE
Question: How to make vine work with hyphenated column name 

### ISSUE THREAD

**Issue by jasonejavier** [vinejs/vine#50]
### Package version

^2.0.0

### Describe the bug

On our AdonisJS model we have a hyphenated column name like this

<img width="304" alt="Screenshot 2024-05-06 at 8 18 00 AM" src="https://github.com/vinejs/vine/assets/33953820/43825157-a820-4ee5-8cdd-a333991e8571">

And we declare it in our consts file like this:

<img width="222" alt="Screenshot 2024-05-06 at 8 19 03 AM" src="https://github.com/vinejs/vine/assets/33953820/588815bd-b1df-4404-b19f-c48b070a5606">

Vine declaration

<img width="481" alt="Screenshot 2024-05-06 at 8 19 34 AM" src="https://github.com/vinejs/vine/assets/33953820/0d59ce25-127c-4d3f-a917-91823be5517c">

We're using the vinejs for checking the body for the CREATE request and when we're passing
`"avs-address": "Sample Address",`

it is giving us the error: `SyntaxError: Missing initializer in const declaration`

Can someone help with this? Thank you!

**Comment by joao-pedro-braz** [comment]
Having the same issue, seems caused by a failure to compile the async function that validates the field

**Comment by RomainLanz** [comment]
Does that fix the issue when you convert the fields to `camelCase`?

https://vinejs.dev/docs/schema_101#converting-the-output-to-camelcase

**Comment by thetutlage** [comment]
Not sure I entirely get the issue. So it will be nice to have a reproduction of the same

**Comment by RomainLanz** [comment]
> Not sure I entirely get the issue. So it will be nice to have a reproduction of the same

The code generated by Vine when using kebab-case field is invalid. The issue reside inside the compiler. Maybe we should normalize the casing of the field inside the generated code.

**Comment by thetutlage** [comment]
> The code generated by Vine when using kebab-case field is invalid

That is what I am trying to figure out. What is invalid? 

- Does it throw a runtime exception? If yes, what does that exception looks like?
- Does it not validate the field altogether? If yes, will need a reproduction
