### ISSUE TITLE
"Cannot find module '@vinejs/vine/types' or its corresponding type declarations."

### ISSUE THREAD

**Issue by Ramank200** [vinejs/vine#52]
### Package version

2.0.0

### Describe the bug

getting error "Cannot find module '@vinejs/vine/types' or its corresponding type declarations."  I'm installing my package using npm i  @vinejs.vine , I was trying to import schematypes from @vinejs/vine/types

**Comment by RomainLanz** [comment]
Hey @Ramanakablah! 👋🏻 

What version of Node.js are you using, and in which project are you installing Vine.js?

**Comment by Ramanakablah** [comment]
Node version is 20.12.2
and the project is a typescript project  (Customer response management )
System.

**Comment by RomainLanz** [comment]
Could you please ensure you have correctly set your `tsconfig` option?

Have a look at this issue: https://github.com/vinejs/vine/issues/3

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
