### ISSUE TITLE
.url() doesn't allow localhost + port urls

### ISSUE THREAD

**Issue by Dolu89** [vinejs/vine#56]
### Package version

2.1.0

### Describe the bug

Hi
When using .url() validator, it can't make http://localhost:3000 a valid URL
It could be great to have this validator when working locally

**Comment by thetutlage** [comment]
Hey, as mentioned in the docs, we use [validator.isURL](https://github.com/validatorjs/validator.js/#:~:text=isURL(str%20%5B%2C%20options%5D)) method for validating URLs. So you will have to probably tweaking some settings to allow `localhost` as the host in the URL.
