### ISSUE TITLE
Question - How to handle DateTime from Luxon with VineJS?

### ISSUE THREAD

**Issue by Venatuss-S** [vinejs/vine#57]
### Package version

1.7.1

### Describe the bug

Hello,
Not sure if I should ask this here but I would like to know how to handle the DateTime type from Luxon with VineJS? I'm using DateTime in my models, but when I use my validator, I have the following error : _Type 'Date | undefined' is not assignable to type 'DateTime | undefined'._ 

Thanks guys!

**Comment by RomainLanz** [comment]
Hey @Venatuss-S! 👋🏻 

You can either create your [own Vine Schema Type](https://vinejs.dev/docs/extend/custom_schema_types) or you can use the [`transform`](https://vinejs.dev/docs/schema_101#transforming-output-value) method to cast the value as a Luxon instance.

```ts
vine.date().transform((v) => DateTime.fromJSDate(v))
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by guoyunhe** [comment]
@RomainLanz possible to provide a way to globally configure this transform? Like:

```js
// config/vine.ts

vine.config({
  dateTransform: v => DateTime.fromJSDate(v)
});
```
