### ISSUE TITLE
Missing export for VineNativeEnum

### ISSUE THREAD

**Issue by simoneNEMO** [vinejs/vine#59]
### Package version

v2.1.0

### Describe the bug

The schema class `VineNativeEnum` is not currently exported while all other schema classes are. This causes the error by the Typescript compiler:
```
error TS2742: The inferred type of 'foo' cannot be named without a reference to '../../node_modules/@vinejs/vine/build/src/schema/enum/native_enum.js'. This is likely not portable. A type annotation is necessary.
```

**Comment by thetutlage** [comment]
Does this error happens when you have `declarations: true` in your `tsconfig.json` file?

**Comment by simoneNEMO** [comment]
Yes that is the case. Thanks for merging!
