### ISSUE TITLE
Question: Getting SyntaxError: "Cannot use import statement outside a module" when execute jest unit tests.

### ISSUE THREAD

**Issue by rgaAlexcobar** [vinejs/vine#67]
### Package version

@vinejs/vine: 2.1.0

### Describe the bug

The error trace is:
node_modules/@vinejs/vine/build/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {...
 
 SyntaxError: Cannot use import statement outside a module
 
I'm testing a file where vine is imported like this:
import vine, { errors } from "@vinejs/vine";

I have done all configurations related to jest to support modules and transform:
this is my jest.config.js:
![image](https://github.com/user-attachments/assets/195843a0-752e-4020-80c3-00e2acb67f4e)

this is my tsconfig.json
![image](https://github.com/user-attachments/assets/59e2bb06-7b63-4b49-982a-eb8197b8e04b)

jest version is 29.7.0

Thanks for any help.

**Comment by thetutlage** [comment]
VineJS is an ESM only package and you are trying to use it inside a CommonJS project
