### ISSUE TITLE
Question - How can I write a custom string validator?

### ISSUE THREAD

**Issue by tcurdt** [vinejs/vine#68]
### Package version

@vinejs/vine@2.1.0 

### Describe the bug

Sorry, but opening the other issue types did somehow not work 🤔

I have a blacklist dictionary and I don't want to provide that as an array. I would like to write my own string validator. But I am somehow not seeing any docs on that. And looking at the code it also does not seem to vine allows for this

https://github.com/vinejs/vine/blob/develop/src/schema/string/main.ts#L300

**Comment by thetutlage** [comment]
Docs already cover it here. https://vinejs.dev/docs/extend/custom_rules

Try to implement a rule and create issues around specific hurdles you face.
