### ISSUE TITLE
[warning] : when building on netlify, Module "node:dns/promises" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by Lost-Saint** [vinejs/vine#69]
### Package version

2.1.0

### Describe the bug

not sure if important.

[plugin:vite:resolve] [plugin vite:resolve] Module "node:dns/promises" has been externalized for browser compatibility, imported by "/opt/build/repo/node_modules/.pnpm/@vinejs+vine@1.8.0/node_modules/@vinejs/vine/build/chunk-TVEIURSI.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by RomainLanz** [comment]
Vine was built to be used on the server, not on a client.

We added a few changes to make it work with some caveats on the front end. You probably used a rule that is only made for the server, like `isActiveURL`.

**Comment by Lost-Saint** [comment]
thx
