### ISSUE TITLE
Add AJV.js to benchmarks

### ISSUE THREAD

**Issue by robahtou** [vinejs/vine#7]
### Package version

latest

### Describe the bug

There is something up with trying to click on the 'feature request' button when creating a new issue, so I am putting it here.

It would be good to add for benchmark comparision  AJV.js https://github.com/ajv-validator/ajv

**Comment by thetutlage** [comment]
Feel free to send a PR for the same

**Comment by abenhamdine** [comment]
you could also compare to https://github.com/icebob/fastest-validator

see https://github.com/icebob/validator-benchmark for its benchmark

**Comment by lolo32** [comment]
I have just tried to add Ajv and Joi to the benchmarks, and each time, Ajv is faster, but there are many more code to write/maintains. This is a choice.

But VineJS arrived seconds, near than Ajv, with a lot more easier syntax to read/maintains
