### ISSUE TITLE
Vine Enum with nullable

### ISSUE THREAD

**Issue by kevinmelo** [vinejs/vine#70]
### Package version

latest

### Describe the bug

When i validate using VineJs and one of the keys is a enum but can be null it's give me de following error:

`TypeError: Cannot convert undefined or null to object
              at Function.values (<anonymous>)
              at _VineNativeEnum `
              
 with the following json:
 
 ```js
 {
    "object": "my_object",
    "entry": [
        {
            "id": "0",
            "time": 1723073445,
            "changes": [
                {
                    "field": "any_field",
                    "value": {
                        "event": "APPROVED",
                        "message_template_id": 12345678,
                        "message_template_name": "my_message_template",
                        "message_template_language": "pt-BR",
                        "reason": null
                    }
                }
            ]
        }
    ]
}
 ```
 
The Complete vine schema:
```js
export default vine.compile(
    vine.object({
        object: vine.string(),
        entry: vine.array(
            vine.object({
                id: vine.string(),
                time: vine.number(),
                changes: vine.array(
                    vine.object({
                        field: vine.string(),
                        value: vine.object({
                            event: vine.enum(OTHER_ENUM),
                            message_template_id: vine.number(),
                            message_template_name: vine.string(),
                            message_template_language: vine.string(),
                            reason: vine.enum(MY_ENUM).nullable(),
                        }),
                    })
                ),
            })
        ),
    })
)
```
 
 Where the erro occurs
 `reason: vine.enum(MY_ENUM).nullable(),`

**Comment by thetutlage** [comment]
Can you please share the complete Vine schema

**Comment by kevinmelo** [comment]
> Can you please share the complete Vine schema

Sure, i update the first comment with the Vine Schema

**Comment by thetutlage** [comment]
Added a test that confirms that enums can be `null` + `nullable`. Feel free to re-open this issue with a failing test and then I will look into it

**Comment by kevinmelo** [comment]
@thetutlage 
Well, still getting error, and this time in a simple validation.

if i declare in this way:

```js
import vine from '@vinejs/vine'
import { EnumTypeXml } from '#controllers/lot/ControllerLotDownloadXml'

export default vine.compile(
    vine.object({
        id: vine.number(),
        type: vine.enum(EnumTypeXml),
    })
)
```

its give me the error `TypeError: Cannot convert undefined or null to object at Function.values (<anonymous>) at _VineNativeEnum`

BUT if i declare in this way:
```js
import vine from '@vinejs/vine'

export default vine.compile(
    vine.object({
        id: vine.number(),
        type: vine.enum(['ENUM_1', ENUM_2]),
    })
)
```

it's work!

any idea?

**Comment by kevinmelo** [comment]
Doing some more tests, looks like have something about the way and where is comming the enum. if i declare the Enum inside the validator it's works, but if i declare inside my controller give me the error
