### ISSUE TITLE
Question - Recursive objects

### ISSUE THREAD

**Issue by keironlowe-edriving** [vinejs/vine#76]
Hi, I'm trying to build some validation that can handle recursive objects and I'm hitting against a TS error. Trying to figure out the best way to handle this.

For the following JSON, the `conditions` array can either be a `condition` object, or `group` object, the `group` object can have a `conditions` array which again, can have either `group` or `condition` object, and this can go on recursively.

```json
{
    "type": "group",
    "inclusive": "true",
    "matchDescription": "example text",
    "conditions": [
        {
            "type": "condition",
            "conditionId": "status",
            "config": {
                "value": "active"
            }
        },
        {
            "type": "group",
            "inclusive": "true",
            "conditions": [
                {
                    "type": "condition",
                    "conditionId": "score",
                    "config": {
                        "value": "50",
                        "operator": "lessThan"
                    }
                },
                {
                    "type": "condition",
                    "conditionId": "score",
                    "config": {
                        "value": "0",
                        "operator": "notEqualTo"
                    }
                }
            ]
        }
    ]
}
```

I'm mostly there with it with the following code...

```ts

const specConditionValidator = vine.object({
  type: vine.literal('condition'),
  conditionId: vine.string(),
  config: vine.object({}).allowUnknownProperties(),
})

const specGroupValidator = vine.object({
  type: vine.literal('group'),
  inclusive: vine.boolean(),
  conditions: vine.array(
    vine.union([
      vine.union.if((value) => value.type === 'group', specGroupValidator),
      vine.union.if((value) => value.type === 'condition', specConditionValidator),
    ])
  ),
})

export const specValidator = vine.compile(
  vine.object({
    ...specGroupValidator.getProperties(),
    matchDescription: vine.string(),
  })
)
```

But the problem is the `vine.union.if((value) => value.type === 'group', specGroupValidator),` line, which throws a TS error saying "Cannot access 'specGroupValidator' before initialization", which makes sense. I'm just not sure of the best way to work around this using Vine.

Thanks!

**Comment by keironlowe-edriving** [comment]
I resolved that error by making `specGroupValidator` a function which returns the vine object. But it now throws a maximum call stack size exceeded error.

From the looks if it, Vine doesn't support recursive objects?

**Comment by RomainLanz** [comment]
Hey @keironlowe-edriving! 👋🏻 

The issue is not Vine directly but how JS works with recursion if you get a `maximum call stack size exceeded`.

I wonder how deep your object is. The call stack size could reach 3200 called functions, so maybe you have an infinite loop going on somewhere.

**Comment by keironlowe-edriving** [comment]
Thanks, yes you're absolutely right. It was a stupid moment from me, I was thinking of this as more of an interface, not realising that it would recursively keep building a massive object forever. 

Guessing there is no way to handle my use case using Vine, I may have to use a JSON schema validator instead. Thanks anyway!
