### ISSUE TITLE
Infer returns incorrect type for object with optional properties

### ISSUE THREAD

**Issue by aadamcik** [vinejs/vine#78]
### Package version

2.1.0

### Describe the bug

Using Infer on vine.object generates incorrect type for optional properties.
```ts
const schema = vine.object({
  name: vine.string().optional(),
})

type Schema = Infer<typeof schema>
// generates type
type Schema = {
  name: string | undefined
}
```

It should generate property as optional. As if no data is provided, it will be completely omitted from resulting object.
```ts
type Schema = {
  name?: string
}
```

**Comment by TzviPM** [comment]
Not sure if this is a regression related to the fix here, but I am defining a schema without optional fields:

```
const authSchema = vine.object({
  email: vine.string().email(),
  password: vine
    .string()
    .minLength(8)
    .maxLength(32)
})
```

And a function with parameter `formData: FormData`

When I try to validate this schema:

```
const data = await vine.validate({
    schema: authSchema,
    data: formData,
  });
```

I see the following type for `data`:

```
const data: {
    email?: string;
    password?: string;
}
```

I will open a new bug for this, but wanted to flag it here too.
