### ISSUE TITLE
Validation issues with object that have dots in the object keys

### ISSUE THREAD

**Issue by kaldray** [vinejs/vine#82]
### Package version

2.1.0

### Describe the bug

When I try to validate a payload that have dot on the object key, the vine compiler reports an issue. Like this : 

```js
{
  'hub.mode': "string",
  'hub.challenge': "string",
  'hub.verify_token': "string",
}
```
First I tried : 

```js
const verificationRequestSchema = vine.object({
  'hub.mode': vine.literal('subscribe'),
  'hub.challenge': vine.number(),
  'hub.verify_token': vine.literal('env'),
})
```
It gave me a compiler error.

As a workaround, I tried to do this : 

```js
const verificationRequestSchema = vine.object({
  hub: vine.object({
    mode: vine.literal('subscribe'),
    challenge: vine.number(),
    verify_token: vine.literal("value"),
  })
})
```
But it didn't work, it redirects me to base path instead and no error.

To reproduce the bug, you have to visit after starting the project : [bug reproduction](http://localhost:3333/deep?hub.mode=subscribe&hub.challenge=1158201444&hub.verify_token=meatyhamhock)

You can find a link to the issue on the Discord here : [Discord discussion](https://discord.com/channels/423256550564691970/1310277506716401735)

### Reproduction repo

https://github.com/kaldray/vine-dot-values

**Comment by thetutlage** [comment]
How does the data object look at your end that you expect to pass the validation?

**Comment by kaldray** [comment]
If I follow the parameters passed on the reproduction link, it should be like : 

```js
{
  "hub.mode":"subscribe",
  "hub.challenge":1158201444,
  "hub.verify_token":"meatyhamhock"
}
```
