### ISSUE TITLE
Discussion for a new feature - Branded Types

### ISSUE THREAD

**Issue by marcuspoehls** [vinejs/vine#85]
Branded types are handy for defining a unique type based on commonly shared types

- https://x.com/mattpocockuk/status/1625173887590842369

I couldn’t find something related to branded types in the Vine docs. Is it possible to define a branded type in the validation schema for a given property?

We use branded types in our apps. Currently, we validate incoming values as strings. Then, we cast validated values for their branded-type companion. Could we define the branded type in the Vine schema already?

**Comment by RomainLanz** [comment]
Hey @marcuspoehls! 👋🏻 

You can use the `transform` property to adjust your type to the desired value. Here’s an example with the `Opaque` helper from AdonisJS.


```ts
import type { Opaque } from '@adonisjs/core/types/helpers'

type UUID = Opaque<string, 'UUID'>;

vine.compile(
  vine.object({
    id: vine.string().uuid().transform((v) => v as UUID),
  })
)

**Comment by marcuspoehls** [comment]
@RomainLanz Awesome! Works nicely, I just tried it directly 🙂 Thank you!

**Comment by thetutlage** [comment]
Hello @marcuspoehls 

Sharing what I did in one of my own projects. Incase you want a more tighter setup. I ended up creating a custom Vine schema for UUIDs and here's the implementation.

```ts
import { Opaque } from '@adonisjs/core/types/helpers'
import { FieldOptions, Validation } from '@vinejs/vine/types'
import { Vine, VineString, BaseLiteralType, symbols } from '@vinejs/vine'

type UUID = Opaque<string, 'UUID'>
class VineUUID extends BaseLiteralType<UUID, UUID, UUID> {
  [symbols.UNIQUE_NAME] = 'vine.uuid';
  [symbols.IS_OF_TYPE] = (value: unknown) => {
    return typeof value === 'string'
  }

  constructor(options?: Partial<FieldOptions>, validations?: Validation<any>[]) {
    super(options, validations)
    this.use(VineString.rules.uuid())
  }

  clone(): this {
    return new VineUUID(this.cloneOptions(), this.cloneValidations()) as this
  }
}

Vine.macro('uuid', function () {
  return new VineUUID()
})

declare module '@vinejs/vine' {
  interface Vine {
    uuid(): VineUUID
  }
}
```

And now you can use it follows.

```ts
vine.object({
  id: vine.uuid(),
})
```

**Comment by marcuspoehls** [comment]
@thetutlage that’s sweet! Thank you for sharing your code for the UUID schema 🙂 

At first impression, this feels like the level of integration I want in my code 😄 And I can already see a handful of places where this extension would make it seamless for the team to chain a method in the validation and the type resolves correctly.

**Comment by aaandrader** [comment]
Using the vineUUID gives me the following error:
`"type": "TypeError", "message": "vine.uuid is not a function"`
