### ISSUE TITLE
Can't use it on Vercel

### ISSUE THREAD

**Issue by emaia** [vinejs/vine#9]
### Package version

1.4.1

### Describe the bug

I know it's not a Vine bug but can't use it on Vercel for now.

```
21:16:48.408 | error @vinejs/vine@1.4.1: The engine "node" is incompatible with this module. Expected version ">=18.16.0". Got "18.15.0"
21:16:48.408 | error Found incompatible module.
21:16:48.408 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
21:16:48.443 | Error: Command "yarn install" exited with 1
21:16:48.952 | BUILD_UTILS_SPAWN_1: Command "yarn install" exited with 1
```

**Comment by thetutlage** [comment]
Doesn't Vercel allows using a custom version of Node.js?

Meanwhile, the Node version 18.16.0 is the LTS, so that should be supported I suspect

**Comment by emaia** [comment]
> Doesn't Vercel allows using a custom version of Node.js?
> 
> Meanwhile, the Node version 18.16.0 is the LTS, so that should be supported I suspect

Tried it but it's not supported.

```
Warning: Detected "engines": { "node": ">=18.16.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
```

**Comment by thetutlage** [comment]
Closing since not actionable
